spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tbl_boards?characterEncoding=UTF-8
    username: testuser
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        highlight_sql: true
logging:
  level:
    # 디버그 레벨로 쿼리 출력
    org.hibernate.SQL: debug
    # ? 파라미터 보여줌
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    root: info


profiles:
  active: dev


